In [7]:
# self-attention
import numpy as np
import pandas as pd
import keras
from keras import layers

In [ ]:
B = 1 ;T = 3 ; d = 2

X = np.array([
    [[1,0], [0,1], [1,1]]
])

print(X) ; print("shape:", X.shape)

[[[1 0]
  [0 1]
  [1 1]]]
shape: (1, 3, 2)


In [22]:
query = X
key = X
value = X

print("Q:", query)
print("shape:", query.shape)

# key transpose
key_t = np.transpose(key, (0,2,1))
print("key_t:", key_t)
print("shape:", key_t.shape)

# QK^T
score = np.matmul(query, key_t)
print("QK^T:", score)

# softmax
def softmax(x):
    e = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e / np.sum(e, axis=-1, keepdims=True)

S = softmax(score)
print("softmax:", S)

# final output
out = np.matmul(S, value)
print("output:", out)

Q: [[[1 0]
  [0 1]
  [1 1]]]
shape: (1, 3, 2)
key_t: [[[1 0 1]
  [0 1 1]]]
shape: (1, 2, 3)
QK^T: [[[1 0 1]
  [0 1 1]
  [1 1 2]]]
softmax: [[[0.4223188  0.1553624  0.4223188 ]
  [0.1553624  0.4223188  0.4223188 ]
  [0.21194156 0.21194156 0.57611688]]]
output: [[[0.8446376  0.5776812 ]
  [0.5776812  0.8446376 ]
  [0.78805844 0.78805844]]]


In [17]:
# B : batch size
# T : token 
# embed_dim : embedding vector dimension
# inputs: (B, T, embed_dim)
# att_dim: query, key, value vector dimension, attention hidden dimension

def self_attention(inputs, att_dim):

    print(inputs) ; print(att_dim)

    # Dense : Input vector Linear transformation?  
    # XW+b??
    query = layers.Dense(att_dim)(inputs)
    key = layers.Dense(att_dim)(inputs)
    value = layers.Dense(att_dim)(inputs)

    print(query)
    print(key)
    print(value)

    # axes 0, 1, 2 -> 0,2,1  
    key_t = keras.ops.transpose(key, axes=(0,2,1))
    print(key_t)
    # dot product
    query_key_dot = keras.ops.matmul(query, key_t) / keras.ops.sqrt(att_dim)
    print(query_key_dot)
    # softmax 
    score = keras.activations.softmax(query_key_dot)
    print(score)
    # dot product, final attention score return
    return keras.ops.matmul(score, value)

In [ ]:
self_attention(X, att_dim=1)



[[[1 0]
  [0 1]
  [1 1]]]
1
tf.Tensor(
[[[-0.05660927]
  [-0.0183413 ]
  [-0.07495058]]], shape=(1, 3, 1), dtype=float32)
tf.Tensor(
[[[-1.0580399 ]
  [ 0.44350088]
  [-0.614539  ]]], shape=(1, 3, 1), dtype=float32)
tf.Tensor(
[[[-0.72744685]
  [ 0.10009408]
  [-0.6273528 ]]], shape=(1, 3, 1), dtype=float32)
tf.Tensor([[[-1.0580399   0.44350088 -0.614539  ]]], shape=(1, 1, 3), dtype=float32)
tf.Tensor(
[[[ 0.05989487 -0.02510626  0.03478861]
  [ 0.01940583 -0.00813438  0.01127145]
  [ 0.0793007  -0.03324065  0.04606006]]], shape=(1, 3, 3), dtype=float32)
tf.Tensor(
[[[0.34557623 0.31741565 0.33700812]
  [0.3372984  0.32813588 0.33456582]
  [0.3495445  0.31233913 0.3381164 ]]], shape=(1, 3, 3), dtype=float32)


<tf.Tensor: shape=(1, 3, 1), dtype=float32, numpy=
array([[[-0.4310399 ],
        [-0.422413  ],
        [-0.43513003]]], dtype=float32)>